[package]
name = "dingir-exchange"
version = "0.1.0"
authors = ["lispczz <mycinbrin@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
env_logger = "0.7.1"
config_rs = { package = "config", version = "0.10.1" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
prost = "0.6.1"
prost-types = "0.6.1"
bytes = "0.5.6"

futures-core = { version = "0.3.5", default-features = false }
futures-channel = "0.3.5"
futures-util = { version = "0.3.5", default-features = false }

tokio = { version = "0.2", features = ["full"] }
thread-id = "3.3.0"
futures = "0.3.5"
hyper = "0.13.7"
crossbeam-channel = "0.4.4"
rdkafka = "0.24.0"
nix = "0.18.0"
anyhow = "1.0.32"
sqlx = { version = "0.4.2", features = [ "runtime-tokio-rustls", "postgres", "chrono", "decimal", "json", "migrate" ] }
chrono = "0.4.15"
rust_decimal = { version = "1.8.1", features = ["postgres", "diesel", "bytes", "byteorder"] }
rust_decimal_macros = "1.8.1"

ttl_cache = "0.5.1"
itertools = "0.9.0"
dotenv = "0.15.0"
num_enum = "0.5.1"
tonic = "0.3.1"
actix-web = "3.3.2"

[target.'cfg(windows)'.dependencies]
rdkafka = { version = "0.24.0", features = ["dynamic_linking"] }

[build-dependencies]
prost = "0.6.1"
tonic-build = "0.3.1"
[[bin]]
name = "rest_api"
path = "src/rest_api.rs"
