version: '3.4'
services:
  envoy:
    image: envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2
    container_name: exchange_envoy
    restart: always
    ports:
      - "8765:8765"
    command: -c /etc/envoy/envoy.yaml --log-level debug
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml   
      - ../proto/matchengine.pb:/tmp/envoy/proto.pb
  db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: exchange_pq
    restart: always
    volumes:
      - ./data/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange_AA9944

  zookeeper:
    image: zookeeper
    container_name: exchange_zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./data/volumes/log_zookeeper:/var/log/zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: exchange_kafka
    restart: always
    logging:
      options:
        max-size: 10m
    ports:
      - "9092:9092"
    volumes:
      - ./data/volumes/log_kafka:/var/log/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "trades:1:1,orders:1:1,balances:1:1,internaltransfer:1:1,registeruser:1:1,unifyevents:1:1"
